### ISSUE TITLE
t411 ne s'affiche pas dans la liste

### ISSUE THREAD

**Issue by Surfoo** [geraldgg/CouchPotato-t411-custom_plugin#16]
Bonjour,

J'ai installé les 2 plugins dans le dossier, et après redémarrage je n'ai que cpasbien qui s'affiche dans Searcher et dans les logs, mais impossible d'avoir T411 et aucuns logs d'erreur non plus. Les fichiers .pyc ont bien été crées dans le dossier pourtant.

Une idée ?

**Comment by thenamelessthing** [comment]
Tu dois t'assurer que le dossier t411 est bien directement dans le dossier custom_plugins et non dans un sous-dossier.

Par exemple quand on fait un git clone dans le dossier custom plugins il créer un dossier contenant cpasbien et un sous dossier t411, tu n'as qu'a remonter le dossier t411 directement dans le dossier custom_plugins.

**Comment by Surfoo** [comment]
C'est déjà le cas, voilà un tree du dossier custom_plugins : 
![plugins](https://cloud.githubusercontent.com/assets/553659/20902489/aba8388e-bb37-11e6-8be8-56fb17f759d8.jpg)

**Comment by thenamelessthing** [comment]
Le mien est comme ceci:

![image](https://cloud.githubusercontent.com/assets/10235448/20910936/a04669d4-bb32-11e6-9701-594ee3a3f879.png)


Si tu effaces ton fichier main.pyc?
Tu es bien propriétaire des fichiers? Quels sont les permissions sur ces fichiers?

**Comment by Surfoo** [comment]
J'ai effacé les 2 fichiers .pyc, restarté couchpotato, mis un +x sur *.pyc et couchpotato est bien l'owner des fichiers (et du pid accessoirement)

**Comment by tocks53** [comment]
bonjours, je suis dans le même cas. J'ai bien mis les fichier mais couch ne les trouve pas dans les log pas d'erreur

admin@Data-1:/volume1/@appstore/couchpotatoserver-custom/var/custom_plugins/t411$ ls -l
total 12
-rwxrwxrwx 1 couchpotatoserver-custom root 2715 Jan  8 15:47 __init__.py
-rwxrwxrwx 1 couchpotatoserver-custom root 4980 Jan  8 16:12 main.py
admin@Data-1:/volume1/@appstore/couchpotatoserver-custom/var/custom_plugins/t411$

**Comment by Surfoo** [comment]
Je viens d'afficher les log.debug dans le code de CouchPotato et voilà ce que ça indique au restart : 

> 03-27 10:46:56 INFO [couchpotato.core.loader] Loaded custom_plugins: cpasbien
03-27 10:46:56 DEBUG [couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "/opt/couchpotato/couchpotato/core/loader.py", line 169, in loadModule
    return import_module(name)
  File "/opt/couchpotato/libs/importhelper/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/opt/couchpotato/custom_plugins/t411/__init__.py", line 2, in <module>
    from .updater import ST411Updater
ImportError: No module named updater

Et si je commente le code concernant l'import du module et l'update, ça fonctionne.

**Comment by Surfoo** [comment]
Ah mais en fait le code a été recopié depuis https://github.com/cocazoulou/ et dans ce dépôt on trouve le fichier updater.py : https://github.com/cocazoulou/couchpotato.provider.t411/blob/master/t411/updater.py
