### ISSUE TITLE
error with t411

### ISSUE THREAD

**Issue by MotorSportF1** [geraldgg/CouchPotato-t411-custom_plugin#18]
There is a error when load this module "t411"
Il y a une erreur lors de chargement de ce module "t411"

Error:
03-29 19:45:42 INFO [0m[  couchpotato.core.loader] Loaded custom_plugins: cpasbien[0m
03-29 19:45:42 DEBUG [36m[  couchpotato.core.loader] Skip loading module plugin t411: Traceback (most recent call last):
  File "/usr/local/couchpotato/couchpotato/core/loader.py", line 169, in loadModule
    return import_module(name)
  File "/usr/local/couchpotato/libs/importhelper/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/couchpotato/data/custom_plugins/t411/__init__.py", line 2, in <module>
    from .updater import ST411Updater
ImportError: No module named updater
[0m

**Comment by Surfoo** [comment]
It's a duplicate with #16
